In [3]:
import torch
import torch.nn as nn

In [2]:
x=torch.arange(0,5)

In [3]:
x


tensor([0, 1, 2, 3, 4])

In [9]:
x=torch.arange(0,5).unsqueeze(1).expand(5,10)


In [10]:
x


tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [11]:
a=[1,2,3,4]
b=a[:-1]
b

[1, 2, 3]

In [13]:
x=x.reshape(25,2)
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2],
        [3, 3],
        [3, 3],
        [3, 3],
        [3, 3],
        [3, 3],
        [4, 4],
        [4, 4],
        [4, 4],
        [4, 4],
        [4, 4]])

In [16]:
x.reshape(-1,5)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]])

In [8]:
import torch 
import torch.nn as nn
import numpy as np
import torch.nn.functional as F

In [ ]:
import os
from copy import deepcopy
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple
from datasets import load_dataset, set_caching_enabled
import numpy as np
from PIL import Image
import torch
import torch.nn as nn
from transformers import (
    # Preprocessing / Common
    AutoTokenizer, AutoFeatureExtractor,  
    # Misc
    logging
)

from sklearn.metrics import accuracy_score, f1_score

# SET CACHE FOR HUGGINGFACE TRANSFORMERS + DATASETS
os.environ['HF_HOME'] = os.path.join(".", "cache")
# SET ONLY 1 GPU DEVICE
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

set_caching_enabled(True)
logging.set_verbosity_error()

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [1]:
class MANN(nn.Module):
    
    def __init__(self,):
        super(MANN,self).__init__()
        self.num_

SyntaxError: unexpected EOF while parsing (<ipython-input-1-0084013249dc>, line 1)

In [ ]:
class Encoder(nn.Module):


In [9]:
class CoAttention(nn.Module):
    def __init__(self,):
        super(VQAModel,self).__init__()
        slef.tanh=nn.tanh()
        self.wv=nn.Parameter()
        self.wh=nn.Parameter()
        self.wm=nn.parameter()
        self.wq=nn.Parameter()
        
    def forward(self,img,qst): 
        mo=torch.mul(img,qst) #img: B x 512 x N
        N=torch.size(img)[2]
        T=torch.size(qst)[2]
        vo=self.tanh(torch.mul(torch.sum(img,dim=2),1/N) 
        qo=torch.mul(torch.sum(img,dim=2),1/T)
        x=self.tanh(torch.matmul(self.wm,mo))
        hn=torch.mul(self.tanh(torch.matmul(self.wv,img)),x)
        ht=torch.mul(self.tanh(torch.matmul(self.wq,qsr)),x)
        alphan=F.softmax(torch.matmul(self.wh,hn),dim=2)
        alphat=F.softmax(torch.matmul(self.wh,ht),dim=2)
        v=self.tanh(torch.sum(torch.matmul(alphan,img),dim=2))
        q=torch.sum(torch.matmul(alphan,qst),dim=2)
        x=torch.cat(v,q)
        return x

In [ ]:
class MANN(nn.Module):
    def __init__(self,batch,row,col):
        super(MANN,self).__init__()
        self.n=row
        self.m=col
        self.memory=torch.rand(row,col)
        self.lstm=nn.LSTM()
        self.cosine=nn.CosineSimilarity()
        self.gamma=0.95
        self.wtu=torch.zeros(batch,col)
        self.wtw=torch.zeros(batch,col)
        
    def forward(self,vec,prev):
        ot,(ht,ct)=self.lstm(vec,prev)
        # ot=B x m , # d= B x n
        wtr=F.softmax(F.CosineSimilarity(ot.unsqueeze(1),self.memory.unsqueeze(0)))
        rt=torch.matmul(wrt,self.memory)
        self.wtw=
        self.wtu=gamma*self.wtu+wtr+wtw
        

In [7]:
class VqaModel(nn.Module):

    def __init__(self, embed_size, qst_vocab_size, ans_vocab_size, word_embed_size, num_layers, hidden_size):

        super(VqaModel, self).__init__()
        self.img_encoder = ImgEncoder(embed_size)
        self.qst_encoder = QstEncoder(qst_vocab_size, word_embed_size, embed_size, num_layers, hidden_size)
        self.co_attention = CoAttention(embed_size)
        self.lstm=MANN(word_embed_size,hidden_size,num_layers)
        self.tanh = nn.Tanh()
        self.dropout = nn.Dropout(0.5)
        self.fc1 = nn.Linear(embed_size, ans_vocab_size)
        self.fc2 = nn.Linear(ans_vocab_size, ans_vocab_size)

    def forward(self, img, qst):
        img_feature=self.img_encoder(img)
        qst_encoder=self.qst_encoder(qst)
        combine_feature=self.co_attention(img_feature,qst_feature)
        
        

SyntaxError: unexpected EOF while parsing (<ipython-input-7-ab3c95d3f601>, line 13)

In [15]:
x=torch.randn(6,5,4)
y = torch.sum(x,dim=2)
y

tensor([[-1.8451, -0.3515,  0.9355,  0.2573, -0.4129],
        [ 1.4813, -0.7109,  3.5683,  0.4053, -2.3847],
        [ 0.5110,  1.2358,  1.5478,  1.7154,  2.0890],
        [ 3.1545,  0.9958,  0.2002,  1.3693,  1.5510],
        [ 4.7096,  1.0580, -2.8520,  1.1044, -2.4724],
        [-0.2028,  5.1461, -2.0014, -1.0448, -0.5776]])

In [16]:
z=torch.mul(y,10)

In [17]:
z

tensor([[-18.4508,  -3.5154,   9.3553,   2.5731,  -4.1286],
        [ 14.8128,  -7.1095,  35.6826,   4.0532, -23.8470],
        [  5.1100,  12.3576,  15.4779,  17.1542,  20.8901],
        [ 31.5452,   9.9576,   2.0021,  13.6927,  15.5100],
        [ 47.0957,  10.5800, -28.5197,  11.0445, -24.7240],
        [ -2.0282,  51.4614, -20.0142, -10.4480,  -5.7763]])

In [10]:
x=torch.tensor([[[1,2],[2,3],[12,13]],[[4,5],[6,7],[14,15]],[[8,9],[10,11],[16,17]]])
x.size()

torch.Size([3, 3, 2])

In [11]:
y=torch.tensor([[2,2,2],[3,3,3]])
y.size()
#z=torch.mul(y,x)
#z

torch.Size([2, 3])

In [12]:
z=torch.matmul(y,x)
z

tensor([[[ 30,  36],
         [ 45,  54]],

        [[ 48,  54],
         [ 72,  81]],

        [[ 68,  74],
         [102, 111]]])

In [31]:
x=torch.rand(2,2,3)
print(x.size())

torch.Size([2, 2, 3])


In [34]:
y=x.view(1,-1)
print(y.size())
print(x.size())

torch.Size([1, 12])
torch.Size([2, 2, 3])


In [ ]:
# Batch * 512 * N
# X* 512. (512*Batch*N)
input x*y.  a*b. o m*n

In [35]:
z = x.permute(0,2,1)
print(z.shape)

torch.Size([2, 3, 2])


In [44]:
x=torch.rand(3,1,4)
x

tensor([[[0.1068, 0.1390, 0.8739, 0.4888]],

        [[0.8493, 0.2095, 0.6482, 0.7653]],

        [[0.3347, 0.3420, 0.6482, 0.9015]]])

In [45]:
y=torch.rand(1,5,4)
y

tensor([[[0.5972, 0.5771, 0.1547, 0.5684],
         [0.2786, 0.2047, 0.7883, 0.3405],
         [0.6011, 0.5842, 0.6323, 0.9785],
         [0.4867, 0.0694, 0.5061, 0.9609],
         [0.7157, 0.8365, 0.1765, 0.5468]]])

In [9]:
z=torch.unsqueeze(x,1)
z

tensor([[[0.3440, 0.3215, 0.7998, 0.0162]],

        [[0.4027, 0.1839, 0.2257, 0.3092]],

        [[0.0732, 0.4191, 0.3115, 0.1809]]])

In [16]:
p=torch.matmul(z,y).squeeze(1)
p

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 1x4)

In [12]:
torch.matmul(x,y)

tensor([[0.6594, 0.8127, 0.5172, 0.3291, 0.6717],
        [0.4559, 0.4545, 0.5198, 0.5474, 0.4750],
        [0.5167, 0.5673, 0.3702, 0.4282, 0.3334]])

In [46]:
p=nn.CosineSimilarity(dim=2)
p(x,y)

tensor([[0.5382, 0.9708, 0.8062, 0.8034, 0.4865],
        [0.8586, 0.8532, 0.9380, 0.9400, 0.7963],
        [0.8204, 0.8767, 0.9756, 0.9581, 0.7546]])